### ISSUE TITLE
CBA no longer works after Chrome update

### ISSUE THREAD

**Issue by KsNero** [browser-automation/cba#153]
Hello
After updating Chrome or Windows, but probably Chrome, CBA no longer works properly. The error is on 3 computers

Description: when you click on Play the lines flicker very quickly or jump very quickly from top to bottom without anything working.

Chrome Version 125.0.6422.113
Version CBA: 10.0.0

Error: back.js:1 Uncaught (in promise) 
Error: Cannot read properties of null (reading 'dispatchEvent')
    at A (back.js:1:8716)

**Comment by Manvel** [comment]
Hi @KsNero that's bad, lately CBA has been updated to be compliant with the new Manifest Version 3, there are few breaking changes in that new version. https://chrome-automation.com/mv3 

In order to make CBA work for you I may need more information about your automations. Do you think you can share with me your automation and help reproduce the error? 

To export project: Right click extension icon -> Options -> Import / Export -> Click on affected project.

You can send the project dump here or send it to me using `saroyanm@gmail.com`.

I am currently swamped with my main job, but will ensure to come up with a fix for your case, if you can share reproduction steps with me that will help, thanks.

**Comment by KsNero** [comment]
Thanks for the quick reply.
I sent you the automation by email.
I've tested it again now. It works very irregularly.
After 1-5 runs, the script always stops at point 1, 2 or 3.
It stopped on its own without pressing the Stop button. You can press Play again straight away. That didn't work normally, you had to stop it first.
Always set it to over 100 runs.

What I also noticed, which wasn't there yesterday, is that the text (timer, redirect, click-update...) flashes very quickly.

Thanks

**Comment by KsNero** [comment]
I tested the new version today. 
The version works perfectly. 
There are no errors. It doesn't quit.

Thank you very much
